# -*- coding: utf-8 -*-
"""detect_video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOOay-lz2iClGOF3u6-G4qulUN6wddn0
"""

!pip install -U ultralytics opencv-python imageio

from google.colab import files
files.upload()

import cv2
import imageio.v2 as imageio
from ultralytics import YOLO

# Load YOLOv8 nano model
model = YOLO("yolov8n.pt")

# Open input video
cap = cv2.VideoCapture("input.mp4")

# Open input video
cap = cv2.VideoCapture("input.mp4")

# Get video properties
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS)) or 20

# Video writer
fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out = cv2.VideoWriter("output.mp4", fourcc, fps, (width, height))

frames_for_gif = []

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run YOLO inference
    results = model(frame)

    # Draw detections
    for r in results:
        for box in r.boxes:
            conf = box.conf[0].item()
            if conf > 0.5:
                x1, y1, x2, y2 = map(int, box.xyxy[0])
                class_id = int(box.cls[0])
                label = model.names[class_id]

                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(
                    frame,
                    f"{label} {conf:.2f}",
                    (x1, y1 - 10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.6,
                    (0, 255, 0),
                    2
                )

    # Save frame
    out.write(frame)

    # Save frame for GIF (resize to reduce size)
    gif_frame = cv2.resize(frame, (640, int(640 * height / width)))
    frames_for_gif.append(cv2.cvtColor(gif_frame, cv2.COLOR_BGR2RGB))

# Cleanup
cap.release()
out.release()

# Save GIF
imageio.mimsave("demo.gif", frames_for_gif, fps=8)

print("✅ Detection complete!")
print("📹 Saved: output.mp4")
print("🖼️ Saved: demo.gif")